services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - blue
      - green
    restart: unless-stopped

  blue:
    image: node:18-alpine
    ports:
      - "8081:8080"
    working_dir: /app
    volumes:
      - ./blue-server.js:/app/server.js
    environment:
      - APP_POOL=blue
      - RELEASE_ID=blue-v1.0.0
      - PORT=8080
    command: ["node", "server.js"]
    restart: unless-stopped

  green:
    image: node:18-alpine
    ports:
      - "8082:8080"
    working_dir: /app
    volumes:
      - ./green-server.js:/app/server.js
    environment:
      - APP_POOL=green
      - RELEASE_ID=green-v1.0.0
      - PORT=8080
    command: ["node", "server.js"]
    restart: unless-stopped

networks:
  default:
    name: zero-downtime-network
